<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <DefaultItemExcludes>$(DefaultItemExcludes);Domain\**;Application\**;Infrastructure\**</DefaultItemExcludes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.37.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="Application\InsightStreamAI.Application.csproj" />
    <ProjectReference Include="Infrastructure\InsightStreamAI.Infrastructure.csproj" />
  </ItemGroup>

</Project>
