<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\InsightStreamAI.Application\InsightStreamAI.Application.csproj" />
    <ProjectReference Include="..\InsightStreamAI.Domain\InsightStreamAI.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.77.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.OpenAI" Version="1.77.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Agents.Core" Version="1.77.0" />
    <PackageReference Include="PdfPig" Version="0.1.8" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);SKEXP0110</NoWarn>
  </PropertyGroup>

</Project>
