<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Markdig" Version="0.37.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InsightStreamAI.Application\InsightStreamAI.Application.csproj" />
    <ProjectReference Include="..\InsightStreamAI.Infrastructure\InsightStreamAI.Infrastructure.csproj" />
    <ProjectReference Include="..\InsightStreamAI.ServiceDefaults\InsightStreamAI.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
